spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: device-manager
              uri: http://localhost:8081
              predicates:
                - Path=/device-manager/**
#        - id: billing-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/billing/**

server:
  port: 8080